spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://rohitswami1612_db_user:Rohits1612@cluster0.wmz3451.mongodb.net/quiz_system?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=quiz_system

server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.htmlAuthController.java